### ISSUE TITLE
IndexError: invalid index to scalar variable

### ISSUE THREAD

**Issue by CireS31** [fediazgon/pbt-keras#1]
Hello,

To understand PBT, I am using your github resources.

Launching the example_boston_ds.ipynb I got the following error.
Remark: no issue with the example_boston_ds.py

Please could you help me to solve it?

Best regards

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-60-733eb50ef8ee> in <module>
     13 
     14 res_gs = train_population(population, x_train, y_train, BATCH_SIZE,
---> 15                           TOTAL_STEPS, STEPS_SAVE, VALIDATION_SPLIT)
     16 
     17 show_results(res_gs)

~\Documents\Data Analytics\P_Deep_Learning\PBT\pbt\utils.py in train_population(population, x, y, batch_size, steps, steps_save, validation_split)
     53         for idx, member in enumerate(population):
     54             # One step of optimisation using hyperparameters of 'member'
---> 55             member.step_on_batch(x, y)
     56             # Model evaluation
     57             loss = member.eval_on_batch(x_val, y_val)

~\Documents\Data Analytics\P_Deep_Learning\PBT\pbt\members.py in step_on_batch(self, x, y)
     70         """
     71         scalars = self.model.train_on_batch(x, y)
---> 72         train_loss, _ = scalars[0], scalars[1:]
     73         self.steps_cycle += 1
     74         return train_loss

IndexError: invalid index to scalar variable.

**Comment by fediazgon** [comment]
Thanks for your interest in the project. I will try later and get back to you. Which python and TensorFlow version are you using?

**Comment by CireS31** [comment]
python 3.7.3 and tensorflow 1.13.1

**Comment by fediazgon** [comment]
Commit https://github.com/fediazgon/pbt-keras/commit/86506e9b7f01c73636cdc0cf442d6c2c1141dae1 solves this.
